### ISSUE TITLE
Lighting profiles completeness checklist

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#5733]
There's a lot of things I have intended for some time to move into lighting profiles. In the interest of keeping these from being forgotten, I'll list them out here.

- [ ] Brightpass threshold and possibly other related options there
- [ ] Envmap lighting multiplier(would be new shader feature)
- [ ] lighting.sdr SPEC_FACTOR_NO_SPEC_MAP 
- [ ] lighting.sdr GLOW_MAP_INTENSITY
- [ ] lighting.sdr GLOW_MAP_SRGB_MULTIPLIER
- [ ] shield-impact-f.sdr EMISSIVE_GAIN

I also want to add at least one further designer tool for them

- [ ] Profile switching in-mission with transition time, for smooth interpolation between float values.
- [ ] purely dynamic runtime profile adjustment options, possibly just in Lua so people can make the sexps they actually need for this.

**Comment by MjnMixael** [comment]
If I may.. a default profile for use in tech-room or any place a model can be drawn via scripting's renderTechModel() or renderOverheadModel() would be useful, too.

**Comment by EatThePath** [comment]
Aha, yes that's one I wanted for some time too, I'm adding it to the list.

**Comment by MoerasGrizzly** [comment]
https://github.com/scp-fs2open/fs2open.github.com/issues/5530
And
https://github.com/scp-fs2open/fs2open.github.com/issues/5486

Are things id love to see handled.

I'd also like to be able to give individual ships the ability to temporarily cast emissive light in FRED.
